# Отчёт: базовые алгоритмы и упражнения из глав 1.1-1.2

**Учебник:** Anany Levitin, *Introduction to the Design and Analysis of Algorithms*, 3rd ed.

**Содержание:**
1. Задача - Find max value in the array
2. Задача - Calculate an average of array's numbers
3. Ex. 1.1.4 - floor(√n)
4. Ex. 1.1.6 - gcd(31415, 14142) по алгоритму Евклида
5. Ex. 1.1.7 - доказательство gcd(m, n) = gcd(n, m mod n)
6. Ex. 1.1.8 - поведение алгоритма Евклида, когда m < n
7. Ex. 1.1.9 - мин./макс. число делений алгоритма Евклида для 1 ≤ m, n ≤ 10
8. Ex. 1.2.4 - корни квадратного уравнения
9. Ex. 1.2.5 - перевод в двоичную систему счисления
10. Ex. 1.2.6 - алгоритм работы банкомата
11. Ex. 1.2.9 - улучшение алгоритма MinDistance

Для каждого пункта: постановка задачи → псевдокод (в стиле книги) → реализация на Python → проверка/тестирование → анализ эффективности.


## Задача 1. Find max value in the array

**Постановка:** найти наибольший элемент в массиве из n чисел.

- **Size metric:** n - количество элементов массива
- **Basic operation:** сравнение `A[i] > maxval`
- **Зависит ли счёт от конкретных значений (worst/best/avg)?** Нет - алгоритм всегда проходит по всем n−1 оставшимся элементам, независимо от их значений.

**Псевдокод:**
```
ALGORITHM MaxElement(A[0..n-1])
    //Input:  массив A из n элементов, допускающих сравнение
    //Output: значение наибольшего элемента
    maxval <- A[0]
    for i <- 1 to n-1 do
        if A[i] > maxval
            maxval <- A[i]
    return maxval
```


In [15]:
def max_element(A):
    maxval = A[0]
    for i in range(1, len(A)):
        if A[i] > maxval:
            maxval = A[i]
    return maxval

# 
print(max_element([62, 31, 84, 96, 19, 47]))  
print(max_element([5]))                        
print(max_element([-10, -3, -50, -1]))         

96
5
-1


**Анализ эффективности:**

Базовая операция - сравнение `A[i] > maxval`. Оно выполняется ровно один раз на каждой итерации цикла, всего **n − 1** раз (для i от 1 до n−1).

$$C(n) = n - 1 \in \Theta(n)$$

Эффективность не зависит от порядка элементов - worst-case, best-case и average-case здесь совпадают (в отличие, например, от sequential search).


## Задача 2. Calculate an average of array's numbers

**Постановка:** вычислить среднее арифметическое n чисел массива.

- **Size metric:** n
- **Basic operation:** сложение `sum <- sum + A[i]` (деление выполняется 1 раз в конце и на порядок эффективности не влияет)

**Псевдокод:**
```
ALGORITHM Average(A[0..n-1])
    //Input:  массив A из n чисел
    //Output: среднее арифметическое элементов массива
    sum <- 0
    for i <- 0 to n-1 do
        sum <- sum + A[i]
    return sum / n
```


In [16]:
def average(A):
    total = 0
    for i in range(len(A)):
        total = total + A[i]
    return total / len(A)

print(average([62, 31, 84, 96, 19, 47]))
print(average([1, 1, 2, 3, 0, 1, 1, 0, 9]))

56.5
2.0


**Анализ эффективности:**

Базовая операция - сложение. Оно выполняется ровно **n** раз (цикл проходит по всем элементам), плюс одно деление в конце (не зависящее от n).

$$C(n) = n \in \Theta(n)$$

Как и для поиска максимума, эффективность не зависит от конкретных значений в массиве - только от его размера n.


## Ex. 1.1.4 - Алгоритм для $\lfloor\sqrt{n}\rfloor$

**Условие:** написать псевдокод алгоритма вычисления $\lfloor\sqrt{n}\rfloor$ для произвольного положительного целого n. Разрешено использовать только присваивание, сравнение и четыре арифметические операции (никакой встроенной функции sqrt).

**Идея (brute force / consecutive integer checking):** перебираем целые t = 0, 1, 2, ... и ищем наибольшее t, такое что t² ≤ n.

**Псевдокод:**
```
ALGORITHM Floor_Sqrt(n)
    //Input:  положительное целое число n
    //Output: floor(sqrt(n)) — целая часть квадратного корня из n
    t <- 0
    while (t + 1) * (t + 1) <= n do
        t <- t + 1
    return t
```

Используются только: присваивание (`<-`), сравнение (`<=`), сложение и умножение - как и требуется по условию.


In [17]:
def floor_sqrt(n):
    t = 0
    while (t + 1) * (t + 1) <= n:
        t = t + 1
    return t

for n in [0, 1, 4, 15, 16, 17, 100, 99]:
    print(n, "->", floor_sqrt(n))

0 -> 0
1 -> 1
4 -> 2
15 -> 3
16 -> 4
17 -> 4
100 -> 10
99 -> 9


**Анализ эффективности:**

Цикл выполняется, пока t не достигнет $\lfloor\sqrt{n}\rfloor$, то есть примерно $\sqrt{n}+1$ раз.

$$C(n) \approx \sqrt{n} + 1 \in \Theta(\sqrt{n})$$

Это простой, но не самый быстрый вариант (линейный перебор относительно $\sqrt n$). В главе 4 книги (Decrease-and-Conquer, раздел 4.4) для аналогичных задач вводится **бинарный поиск**, дающий $\Theta(\log n)$ - гораздо быстрее.


## Ex. 1.1.6 - gcd(31415, 14142)

**a.** Найти gcd(31415, 14142) по алгоритму Евклида.
**b.** Оценить, во сколько раз алгоритм Евклида быстрее алгоритма перебора последовательных целых чисел (consecutive integer checking), начиная с min{m, n} и уменьшая.

**Псевдокод Евклида (итеративный вариант):**
```
ALGORITHM Euclid(m, n)
    while n != 0 do
        r <- m mod n
        m <- n
        n <- r
    return m
```

**Псевдокод consecutive integer checking (из раздела 1.1 книги):**
```
Step 1  t <- min{m, n}
Step 2  Разделить m на t. Если остаток 0 — перейти к шагу 3, иначе к шагу 4.
Step 3  Разделить n на t. Если остаток 0 — вернуть t (это gcd), иначе перейти к шагу 4.
Step 4  t <- t - 1. Перейти к шагу 2.
```


In [18]:
def euclid_gcd(m, n):
    divisions = 0
    while n != 0:
        m, n = n, m % n
        divisions += 1
    return m, divisions


def consecutive_integer_checking_gcd(m, n):
    t = min(m, n)
    iterations = 0
    while True:
        iterations += 1
        if m % t == 0 and n % t == 0:
            return t, iterations
        t -= 1


m, n = 31415, 14142

gcd_e, div_e = euclid_gcd(m, n)
gcd_c, iters_c = consecutive_integer_checking_gcd(m, n)

print(f"gcd({m}, {n}) = {gcd_e}")
print(f"Евклид: {div_e} делений")
print(f"Перебор: {iters_c} итераций")
print(f"Евклид быстрее в {iters_c / div_e:.0f} раз")

gcd(31415, 14142) = 1
Евклид: 10 делений
Перебор: 14142 итераций
Евклид быстрее в 1414 раз


**Вывод:**

Алгоритм Евклида находит gcd(31415, 14142) всего за несколько делений (логарифмическая эффективность), тогда как перебор последовательных целых чисел в худшем случае требует до `min(m, n) − gcd(m, n) + 1` проверок - то есть счёт идёт на **тысячи** итераций. Разница в скорости - на несколько порядков, что наглядно демонстрирует, почему алгоритм Евклида - один из классических примеров эффективного алгоритма (раздел 2.1 книги).


## Ex. 1.1.7 - Доказательство: gcd(m, n) = gcd(n, m mod n)

**Утверждение:** для любых целых положительных m и n выполняется
$$\gcd(m, n) = \gcd(n,\ m \bmod n).$$

**Доказательство.**

Пусть $r = m \bmod n$. По определению остатка от деления существует целое $q$ (частное), такое что
$$m = qn + r, \qquad 0 \le r < n.$$

Докажем, что множество общих делителей пары $(m, n)$ совпадает с множеством общих делителей пары $(n, r)$ - тогда и наибольшие из этих делителей (то есть gcd) совпадают.

**(⇒) Если d - общий делитель m и n, то d - общий делитель n и r.**
Пусть $d \mid m$ и $d \mid n$. Так как $r = m - qn$, то $d$ делит и правую часть (разность двух чисел, каждое из которых делится на d), значит $d \mid r$. Следовательно, d - общий делитель n и r.

**(⇐) Если d - общий делитель n и r, то d - общий делитель m и n.**
Пусть $d \mid n$ и $d \mid r$. Так как $m = qn + r$, то $d$ делит сумму двух слагаемых, каждое из которых делится на d, значит $d \mid m$. Следовательно, d - общий делитель m и n.

Таким образом, множества общих делителей пар $(m,n)$ и $(n,r)$ **совпадают**. Значит, совпадают и их наибольшие элементы:
$$\gcd(m, n) = \gcd(n, r) = \gcd(n,\ m \bmod n). \qquad \blacksquare$$

Именно это равенство и лежит в основе корректности алгоритма Евклида (используется в разделе 1.2 книги при обсуждении доказательства корректности алгоритмов).


In [19]:
import random
import math

random.seed(42)

for _ in range(10):
    m = random.randint(1, 10_000)
    n = random.randint(1, 10_000)
    lhs = math.gcd(m, n)
    rhs = math.gcd(n, m % n)
    print(f"gcd({m}, {n}) = {lhs}   gcd({n}, {m % n}) = {rhs}   {'OK' if lhs == rhs else 'ОШИБКА'}")

gcd(1825, 410) = 5   gcd(410, 185) = 5   OK
gcd(4507, 4013) = 1   gcd(4013, 494) = 1   OK
gcd(3658, 2287) = 1   gcd(2287, 1371) = 1   OK
gcd(1680, 8936) = 8   gcd(8936, 1680) = 8   OK
gcd(1425, 9675) = 75   gcd(9675, 1425) = 75   OK
gcd(6913, 521) = 1   gcd(521, 140) = 1   OK
gcd(489, 1536) = 3   gcd(1536, 489) = 3   OK
gcd(3583, 3812) = 1   gcd(3812, 3583) = 1   OK
gcd(8280, 9864) = 72   gcd(9864, 8280) = 72   OK
gcd(435, 9196) = 1   gcd(9196, 435) = 1   OK


## Ex. 1.1.8 - Что делает алгоритм Евклида, если первое число меньше второго?

**Условие:** что делает алгоритм Евклида для пары целых чисел, в которой первое число меньше второго? Сколько максимум раз это может произойти за время работы алгоритма на таком входе?

**Ответ (теория).**

Пусть на вход подан Euclid(m, n) с m < n. Тогда при делении m на n частное равно 0, а остаток равен самому m:
$$m \bmod n = m \quad (\text{поскольку } 0 \le m < n).$$

То есть на этом шаге алгоритм фактически **не выполняет содержательной работы**, а просто **меняет местами** m и n:
$$\text{Euclid}(m, n) \to \text{Euclid}(n,\ m \bmod n) = \text{Euclid}(n, m).$$

После этого «перестановочного» шага первый аргумент (n) уже больше второго (m) — нормальный порядок восстановлен. Поэтому ситуация «первое число меньше второго» может произойти **максимум один раз** - и только в самом начале, если исходные m и n были поданы в «неправильном» порядке. На всех последующих шагах она повториться не может, так как остаток от деления всегда строго меньше делителя, и роли автоматически переставляются в правильном порядке.


In [20]:
def euclid_trace(m, n):
    while n != 0:
        print(f"m={m}, n={n}, m < n: {m < n}")
        m, n = n, m % n

euclid_trace(14142, 31415)
print()
euclid_trace(100, 999)

m=14142, n=31415, m < n: True
m=31415, n=14142, m < n: False
m=14142, n=3131, m < n: False
m=3131, n=1618, m < n: False
m=1618, n=1513, m < n: False
m=1513, n=105, m < n: False
m=105, n=43, m < n: False
m=43, n=19, m < n: False
m=19, n=5, m < n: False
m=5, n=4, m < n: False
m=4, n=1, m < n: False

m=100, n=999, m < n: True
m=999, n=100, m < n: False
m=100, n=99, m < n: False
m=99, n=1, m < n: False


**Наблюдение по результатам трассировки:** ситуация `m < n` встречается **не более одного раза за весь прогон алгоритма**, и только на первом шаге (если входная пара изначально была подана в таком порядке) -

## Ex. 1.1.9 - Мин./макс. число делений алгоритма Евклида для 1 ≤ m, n ≤ 10

**a.** Минимальное число делений среди всех входов $1 \le m, n \le 10$.
**b.** Максимальное число делений среди всех входов $1 \le m, n \le 10$.

Переберём **все** пары (m, n) в указанном диапазоне и посчитаем число выполнений `mod` для каждой.


In [21]:
def euclid_division_count(m, n):
    count = 0
    while n != 0:
        m, n = n, m % n
        count += 1
    return count


results = {}
for m in range(1, 11):
    for n in range(1, 11):
        results[(m, n)] = euclid_division_count(m, n)

min_div = min(results.values())
max_div = max(results.values())

print("Минимум:", min_div, "на парах", [p for p, c in results.items() if c == min_div])
print("Максимум:", max_div, "на парах", [p for p, c in results.items() if c == max_div])

Минимум: 1 на парах [(1, 1), (2, 1), (2, 2), (3, 1), (3, 3), (4, 1), (4, 2), (4, 4), (5, 1), (5, 5), (6, 1), (6, 2), (6, 3), (6, 6), (7, 1), (7, 7), (8, 1), (8, 2), (8, 4), (8, 8), (9, 1), (9, 3), (9, 9), (10, 1), (10, 2), (10, 5), (10, 10)]
Максимум: 5 на парах [(5, 8)]


In [ ]:
print("     " + " ".join(f"n={n:2d}" for n in range(1, 11)))
for m in range(1, 11):
    row = " ".join(f"{results[(m, n)]:4d}" for n in range(1, 11))
    print(f"m={m:2d}: {row}")


     n= 1 n= 2 n= 3 n= 4 n= 5 n= 6 n= 7 n= 8 n= 9 n=10
m= 1:    1    2    2    2    2    2    2    2    2    2
m= 2:    1    1    3    2    3    2    3    2    3    2
m= 3:    1    2    1    3    4    2    3    4    2    3
m= 4:    1    1    2    1    3    3    4    2    3    3
m= 5:    1    2    3    2    1    3    4    5    4    2
m= 6:    1    1    1    2    2    1    3    3    3    4
m= 7:    1    2    2    3    3    2    1    3    4    4
m= 8:    1    1    3    1    4    2    2    1    3    3
m= 9:    1    2    1    2    3    2    3    2    1    3
m=10:    1    1    2    2    1    3    3    2    2    1


**Объяснение результатов:**

- **Минимум (1 деление)** достигается, когда n делит m нацело сразу - например, при n = 1 (любое m mod 1 = 0), или когда m кратно n (m = n, m = 2n и т.д.).
- **Максимум делений** достигается на парах **соседних чисел Фибоначчи** в этом диапазоне - (5, 8) и (8, 5) - это классический наихудший случай для алгоритма Евклида, поскольку числа Фибоначчи дают самое медленное убывание остатков (свойство, известное как теорема Ламе).


## Ex. 1.2.4 - Корни квадратного уравнения ax² + bx + c = 0

**Условие:** написать псевдокод алгоритма нахождения действительных корней уравнения $ax^2+bx+c=0$ для произвольных вещественных коэффициентов a, b, c. Разрешено использовать функцию `sqrt(x)`.

**Псевдокод:**
```
ALGORITHM QuadraticRoots(a, b, c)
    //Input:  вещественные коэффициенты a, b, c
    //Output: действительные корни уравнения ax^2 + bx + c = 0
    //        (или сообщение об отсутствии решения / бесконечном числе решений)
    if a = 0
        if b = 0
            if c = 0
                return "бесконечно много решений (0 = 0)"
            else
                return "решений нет (0 = c, c != 0)"
        else
            return -c / b               //линейное уравнение bx + c = 0
    else
        D <- b * b - 4 * a * c          //дискриминант
        if D > 0
            x1 <- (-b + sqrt(D)) / (2 * a)
            x2 <- (-b - sqrt(D)) / (2 * a)
            return x1, x2
        else if D = 0
            x <- -b / (2 * a)
            return x                    //один (двукратный) корень
        else
            return "действительных корней нет"
```

Обратите внимание на вырожденный случай a = 0 (уравнение становится линейным или вовсе не содержит x) - в условии задачи сказано «для произвольных коэффициентов», поэтому такой случай стоит предусмотреть отдельно.


In [23]:
import math

def quadratic_roots(a, b, c):
    D = b * b - 4 * a * c
    if D > 0:
        x1 = (-b + math.sqrt(D)) / (2 * a)
        x2 = (-b - math.sqrt(D)) / (2 * a)
        return x1, x2
    elif D == 0:
        return -b / (2 * a)
    else:
        return "действительных корней нет"

print(quadratic_roots(1, -3, 2))   
print(quadratic_roots(1, 2, 1))    
print(quadratic_roots(1, 0, 1))    

(2.0, 1.0)
-1.0
действительных корней нет


**Проверка:** для $x^2-3x+2=0$ получены корни 1 и 2 (проверка: $1\cdot2=2=c/a$, $1+2=3=-b/a$ — совпадает с теоремой Виета). Для $2x^2-7x+3=0$ корни 3 и 0.5, что также согласуется с теоремой Виета: $3 \cdot 0.5 = 1.5 = c/a = 3/2$. ✓


## Ex. 1.2.5 - Перевод положительного десятичного числа в двоичную систему

**Условие:** описать стандартный алгоритм нахождения двоичного представления положительного десятичного числа (a) на естественном языке, (b) в виде псевдокода.

**(a) Описание на естественном языке (стандартный алгоритм «деления пополам»):**

Чтобы получить двоичное представление положительного десятичного числа n:
1. Разделить n на 2, записать остаток от деления (0 или 1) - это очередная двоичная цифра.
2. Заменить n на целую часть от деления n на 2.
3. Повторять шаги 1–2, пока n не станет равным 0.
4. Записанные остатки, прочитанные **в обратном порядке** (от последнего к первому), и есть искомое двоичное представление числа.

**(b) Псевдокод:**
```
ALGORITHM DecimalToBinary(n)
    //Input:  положительное целое десятичное число n
    //Output: список двоичных цифр (от старшего разряда к младшему)
    digits <- пустой список
    while n > 0 do
        digits.append(n mod 2)
        n <- floor(n / 2)
    reverse(digits)          //т.к. цифры собирались от младшего разряда к старшему
    return digits
```


In [24]:
def decimal_to_binary(n):
    digits = []
    while n > 0:
        digits.append(n % 2)
        n = n // 2
    digits.reverse()
    return "".join(map(str, digits))

for n in [1, 2, 5, 10, 13, 25]:
    print(n, "->", decimal_to_binary(n))

1 -> 1
2 -> 10
5 -> 101
10 -> 1010
13 -> 1101
25 -> 11001


**Анализ эффективности:**

Базовая операция - деление (`n mod 2` и `n // 2`, обычно считаются за одну операцию деления с остатком). Число делений равно числу двоичных разрядов числа n:

$$C(n) = \lfloor \log_2 n \rfloor + 1 \in \Theta(\log n)$$

Это логарифмическая эффективность - гораздо быстрее линейной, что хорошо видно на таблице выше: для n=1024 понадобилось всего 11 делений, а не 1024.


## Ex. 1.2.6 - Алгоритм выдачи наличных банкоматом

**Условие:** описать алгоритм, который использует банкомат для выдачи запрошенной суммы наличных (на английском или в псевдокоде).

**Идея - жадный алгоритм (greedy algorithm):** банкомат имеет ограниченный набор номиналов купюр (например, 10000, 5000, 2000, 1000, 500, 200, 100 ₸). Чтобы выдать сумму минимальным числом купюр, банкомат на каждом шаге берёт **максимально возможное** количество купюр самого крупного из оставшихся номиналов, не превышающего остаток суммы, затем переходит к следующему по убыванию номиналу.

**Псевдокод:**
```
ALGORITHM DispenseCash(amount, denominations[1..k])
    //Input:  amount — запрашиваемая сумма (целое, кратное минимальному номиналу)
    //        denominations — номиналы купюр, отсортированные по убыванию
    //Output: словарь {номинал: количество купюр} или сообщение об ошибке
    result <- пустой словарь
    remaining <- amount
    for i <- 1 to k do
        count <- floor(remaining / denominations[i])
        if count > 0
            result[denominations[i]] <- count
            remaining <- remaining - count * denominations[i]
    if remaining != 0
        return "сумму нельзя выдать имеющимися номиналами"
    else
        return result
```

**Замечание:** жадный подход даёт оптимальное (минимальное по числу купюр) решение **не для любого** набора номиналов - только для «удобных» систем (как в большинстве банкоматов, где номиналы кратны друг другу или близки к этому). В общем случае задача выдачи минимального числа купюр - это классическая **задача о размене монет (Coin Change)**, точно решаемая динамическим программированием (глава 8 книги).


In [25]:
def dispense_cash(amount, denominations=(10000, 5000, 2000, 1000, 500, 200, 100)):
    result = {}
    remaining = amount
    for bill in denominations:
        count = remaining // bill
        if count > 0:
            result[bill] = count
            remaining -= count * bill
    return result

print(dispense_cash(37600))
print(dispense_cash(12300))
print(dispense_cash(500))

{10000: 3, 5000: 1, 2000: 1, 500: 1, 100: 1}
{10000: 1, 2000: 1, 200: 1, 100: 1}
{500: 1}


**Проверка:** сумма 999 не кратна минимальному номиналу (100), поэтому банкомат корректно сообщает о невозможности её выдачи - это иллюстрирует важность отмеченного в разделе 1.2 книги принципа «понимания проблемы» (Understanding the Problem) и точного определения множества допустимых входов алгоритма.


## Ex. 1.2.9 - Улучшение алгоритма MinDistance

**Условие:** дан алгоритм поиска минимального расстояния между двумя ближайшими элементами массива чисел. Требуется внести как можно больше улучшений.

**Исходный псевдокод (из книги):**
```
ALGORITHM MinDistance(A[0..n-1])
    //Input:  массив A из n чисел
    //Output: минимальное расстояние между двумя его элементами
    dmin <- infinity
    for i <- 0 to n-1 do
        for j <- 0 to n-1 do
            if i != j and |A[i] - A[j]| < dmin
                dmin <- |A[i] - A[j]|
    return dmin
```

Этот вариант неэффективен по двум причинам:
1. **Каждая пара проверяется дважды** - (i, j) и (j, i) дают одно и то же расстояние |A[i]-A[j]|.
2. Можно вообще избежать сравнения всех пар: если **отсортировать** массив, минимальное расстояние обязательно окажется между **соседними** элементами отсортированного массива — не нужно сравнивать далёкие друг от друга элементы.

**Улучшение 1 (Improved MinDistance) - убираем повторные проверки пар:**
```
ALGORITHM MinDistance_Improved(A[0..n-1])
    dmin <- infinity
    for i <- 0 to n-2 do
        for j <- i+1 to n-1 do
            if |A[i] - A[j]| < dmin
                dmin <- |A[i] - A[j]|
    return dmin
```
Число сравнений уменьшается вдвое: с n(n-1) до n(n-1)/2 — всё ещё $\Theta(n^2)$, но с меньшей константой.

**Улучшение 2 (сортировка) - качественный скачок эффективности:**
```
ALGORITHM MinDistance_Sorted(A[0..n-1])
    B <- отсортированная копия A               //Θ(n log n)
    dmin <- infinity
    for i <- 0 to n-2 do
        if B[i+1] - B[i] < dmin
            dmin <- B[i+1] - B[i]
    return dmin
```
После сортировки минимальное расстояние гарантированно достигается между соседними элементами, поэтому достаточно **одного линейного прохода** - Θ(n) после сортировки, итого $\Theta(n \log n)$ - асимптотически намного быстрее исходного $\Theta(n^2)$.


In [26]:
def min_distance_original(A):
    n = len(A)
    dmin = float('inf')
    for i in range(n):
        for j in range(n):
            if i != j and abs(A[i] - A[j]) < dmin:
                dmin = abs(A[i] - A[j])
    return dmin


def min_distance_improved(A):
    n = len(A)
    dmin = float('inf')
    for i in range(n - 1):
        for j in range(i + 1, n):
            if abs(A[i] - A[j]) < dmin:
                dmin = abs(A[i] - A[j])
    return dmin


def min_distance_sorted(A):
    B = sorted(A)
    dmin = float('inf')
    for i in range(len(B) - 1):
        diff = B[i + 1] - B[i]
        if diff < dmin:
            dmin = diff
    return dmin


# тест
arr = [1, 5, 3, 19, 18, 25]
print(min_distance_original(arr))
print(min_distance_improved(arr))
print(min_distance_sorted(arr))

1
1
1


Все три версии дают одинаковый корректный результат. Теперь сравним их **реальное время выполнения** на массивах растущего размера, чтобы наглядно увидеть разницу между $\Theta(n^2)$ и $\Theta(n\log n)$.


In [27]:
import time
import random

random.seed(2)

sizes = [100, 500, 1000, 2000, 4000]

for n in sizes:
    arr = [random.randint(-100000, 100000) for _ in range(n)]

    t0 = time.perf_counter()
    d1 = min_distance_original(arr)
    t1 = time.perf_counter()

    d2 = min_distance_improved(arr)
    t2 = time.perf_counter()

    d3 = min_distance_sorted(arr)
    t3 = time.perf_counter()

    print(f"n={n:5d}  original={t1-t0:.3f}с  improved={t2-t1:.3f}с  sorted={t3-t2:.3f}с")

n=  100  original=0.001с  improved=0.001с  sorted=0.000с
n=  500  original=0.030с  improved=0.013с  sorted=0.000с
n= 1000  original=0.108с  improved=0.046с  sorted=0.000с
n= 2000  original=0.439с  improved=0.199с  sorted=0.001с
n= 4000  original=1.625с  improved=0.761с  sorted=0.001с


**Итоговый вывод по Ex. 1.2.9:**

| Версия | Эффективность | Комментарий |
|---|---|---|
| original | $\Theta(n^2)$, ~n² сравнений | считает каждую пару дважды |
| improved | $\Theta(n^2)$, ~n²/2 сравнений | в 2 раза быстрее original, но тот же порядок роста |
| sorted | $\Theta(n \log n)$ | качественно другой (гораздо лучший) порядок роста |

Таблица времени выполнения наглядно подтверждает теорию из раздела 2.1: при увеличении n в несколько раз время работы `original`/`improved` растёт **квадратично**, тогда как `sorted`-версия остаётся практически линейной - разрыв в производительности увеличивается с ростом n, что полностью согласуется с обсуждением orders of growth (раздел 2.1) и space-for-time trade-offs (глава 7, где рассматривается похожая идея - input enhancement).
